# Generated by Django 4.1.4 on 2023-01-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField(max_length=50)),
                ("last_name", models.TextField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
