# Generated by Django 4.1.4 on 2023-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactme", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactme",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contactme",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
